// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsdt1FpgblQyOFx6a6QD56qPadnzrbU7o',
    appId: '1:460127607830:web:8b217e0d3405bb696aa937',
    messagingSenderId: '460127607830',
    projectId: 'fruits-freshness-detecti-8ee23',
    authDomain: 'fruits-freshness-detecti-8ee23.firebaseapp.com',
    storageBucket: 'fruits-freshness-detecti-8ee23.appspot.com',
    measurementId: 'G-7MZE85NM5R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi9jI1tWAaiX6YgST2_3d2oAZaDPacSqU',
    appId: '1:460127607830:android:22b55692b9a529106aa937',
    messagingSenderId: '460127607830',
    projectId: 'fruits-freshness-detecti-8ee23',
    storageBucket: 'fruits-freshness-detecti-8ee23.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqMWO7bWAivjX4Vs2F2_EBjOr0_7wSRHY',
    appId: '1:460127607830:ios:2594c2604d7ab0916aa937',
    messagingSenderId: '460127607830',
    projectId: 'fruits-freshness-detecti-8ee23',
    storageBucket: 'fruits-freshness-detecti-8ee23.appspot.com',
    iosClientId: '460127607830-h84du4nvnrkm5afc9i28ugqrd648lg0a.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruits',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqMWO7bWAivjX4Vs2F2_EBjOr0_7wSRHY',
    appId: '1:460127607830:ios:2594c2604d7ab0916aa937',
    messagingSenderId: '460127607830',
    projectId: 'fruits-freshness-detecti-8ee23',
    storageBucket: 'fruits-freshness-detecti-8ee23.appspot.com',
    iosClientId: '460127607830-h84du4nvnrkm5afc9i28ugqrd648lg0a.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruits',
  );
}
